		alias ls='ls --color=auto'
		alias dir='dir --color=auto'
		alias vdir='vdir --color=auto'
		alias grep='grep --color=auto'
		alias fgrep='fgrep --color=auto'
		alias egrep='egrep --color=auto'
		alias vi='vim '
		alias c='clear; ls'
		alias cd..='cd ..'
		alias up='cd ..'
		alias ll='ls -lA'
		alias ls='ls --color=auto'
		alias wget='wget -c'
		alias la='ls -A'
		alias l='ls -CF'
		alias xpdf='atril'
		alias e='exit'
		alias wget='wget -c'
		alias mkdir='mkdir -pv'
		alias rm='rm -r'
		function cdl { cd $1; clear;  ls;}
		alias cd='cdl '
		alias sudo='sudo' 
		alias rm='rm -i'
		alias web='cd /var/www/'
		alias update='sudo yum -y update'
		alias install='sudo yum install'
		alias sudo='sudo '
		alias vps='ssh -p 3350 aurbina@192.243.103.185 -YC'
		alias odin='ssh aurbina@odin.cs.csub.edu -YC'
